menu:
  - name: home
    url: /
    newTab: false
  - name: resume
    url: /resume
    newTab: false
  - name: mood
    url: /mood
    newTab: true
  - name: amusement
    url: /amusement/tetris
    newTab: true
  - name: about
    url: /about
    newTab: false

widgets:
  - user-info
  - latest
  - category
  - archive
  - label

favicon: https://www.lylelove.top/media/website/90.png

#UserInfo
avatar: https://avatars.githubusercontent.com/u/61548984?v=4
author: 竟何
slogan: 你想把你的温柔和迷恋一同给他／ 让微凉的风当邮差／ 送给他一封长信／
