name: Hexo Auto Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

# 这里放环境变量,需要替换成你自己的
env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: lylelove
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: lylelove@163.com
  # Hexo 编译后要部署的 github 仓库
  GIT_DEPLOY_REPO: lylelove/blread
  # Hexo 编译后要部署到的分支
  GIT_DEPLOY_BRANCH: gh_page
  # 注意替换为你的 GitHub 源仓库地址
  GIT_SOURCE_REPO: git@github.com:lylelove/blread.git
  # Github源仓库名称
  GIT_REPO_NAME: blread
jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node_version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Clean
        run: |
          git config --global user.email "lylelove@163.com"
          git config --global user.name "lylelove"
          git clone ${{ env.GIT_SOURCE_REPO }}
          cd ${{ env.GIT_REPO_NAME }}
          git pull origin main
          git rm -r --cached source
          git commit -m 'Clean'
          git push -u origin main
        
      - name: Bilibiliupdate
        run: |
          mkdir -p source\_posts
          python3 main.py
          git config --global user.email "lylelove@163.com"
          git config --global user.name "lylelove"
          git add -A
          git commit -m 'Bilibili_update'
          git push origin main

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_DEPLOY_REPO }}
          ref: ${{ env.GIT_DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa e.coding.net >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa gitee.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install
          npm uninstall hexo-generator-index --save
          npm install hexo-baidu-url-submit hexo-generator-index2 hexo-symbols-count-time hexo-blog-encrypt hexo-deployer-git --save

      - name: Deploy hexo
        run: |
          npm remove hexo-baidu-url-submit
          hexo clean
          hexo g
          hexo d
